FROM node:20-alpine

WORKDIR /app

# Không cần sao chép bất kỳ thứ gì vì chúng ta sẽ mount volume

# Cài đặt một số dependencies cơ bản
RUN npm install -g npm@latest
RUN apk add --no-cache bash

EXPOSE 3000

CMD ["npm", "run", "dev"] 