version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: production
    restart: always
    expose:
      - '3001'
    environment:
      - DB_TYPE=sqlite
      - DB_DATABASE=database.sqlite
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    volumes:
      - sqlite_data:/usr/src/app/data
    command: node dist/main
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      target: production
    restart: always
    ports:
      - '80:3000'
      - '443:3000'
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=https://${DOMAIN}/api
      - NODE_ENV=production
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data: 