version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: development
    restart: always
    ports:
      - '3001:3001'
    environment:
      - DB_TYPE=sqlite
      - DB_DATABASE=database.sqlite
      - JWT_SECRET=${JWT_SECRET:-secret_key}
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
      - sqlite_data:/usr/src/app/data
    command: node dist/server.js
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      target: development
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data: 