version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: development
    restart: always
    ports:
      - '3001:3001'
    environment:
      - DB_TYPE=sqlite
      - DB_DATABASE=database.sqlite
      - JWT_SECRET=your_jwt_secret_key
      - NODE_ENV=development
      - PORT=3001
      - HOST=0.0.0.0
      - TS_NODE_TRANSPILE_ONLY=true
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - sqlite_data:/usr/src/app/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data:

